# Generated by Django 5.2 on 2025-04-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.FileField(default='static/img/place_holder_default.jpg', upload_to='D:\\Django-Workspace\\MVshop\\store\\static'),
        ),
    ]
