# Generated by Django 5.2 on 2025-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.FileField(default='static/img/place_holder_default.jpg', upload_to='D:/Django-Workspace/MVshop/store/static/img/'),
        ),
    ]
